// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUs02Y55Lx5TxCxed_OdU7G-5_9neo688',
    appId: '1:909136579948:web:ff54c280c7ccc2740df749',
    messagingSenderId: '909136579948',
    projectId: 'caht-app-77a9d',
    authDomain: 'caht-app-77a9d.firebaseapp.com',
    storageBucket: 'caht-app-77a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnMzqMJmHKEISEpj7clKqg1Q4FqsCS1-w',
    appId: '1:909136579948:android:6ddc5e3d47b2bd460df749',
    messagingSenderId: '909136579948',
    projectId: 'caht-app-77a9d',
    storageBucket: 'caht-app-77a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuheQOUsLBlWcc5D_-a_9CagqW1GB5SFc',
    appId: '1:909136579948:ios:1074be0fd870a6a70df749',
    messagingSenderId: '909136579948',
    projectId: 'caht-app-77a9d',
    storageBucket: 'caht-app-77a9d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuheQOUsLBlWcc5D_-a_9CagqW1GB5SFc',
    appId: '1:909136579948:ios:a5379151d92b3e690df749',
    messagingSenderId: '909136579948',
    projectId: 'caht-app-77a9d',
    storageBucket: 'caht-app-77a9d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
